# Generated by Django 2.2.1 on 2019-05-02 17:11

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='child', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('photo', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('location', models.CharField(default='', max_length=255)),
                ('userType', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='volunteer', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NGOVolunteerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pictures.NGO')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pictures.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='ChildNGOMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pictures.Child')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pictures.NGO')),
            ],
        ),
    ]
