# Generated by Django 2.2.1 on 2019-05-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='photo_name',
            field=models.CharField(default='invalid', max_length=255),
        ),
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
