# Generated by Django 2.2.1 on 2019-05-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20190502_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngovolunteermap',
            name='volunteer',
        ),
    ]
